[project]
name = "dicta"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch>=2.6.0",
    "tqdm>=4.67.1",
    "transformers>=4.50.0",
]
